# Generated by Django 5.0.6 on 2024-05-10 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="description",
            field=models.TextField(max_length=5000),
        ),
    ]
