# Generated by Django 5.0.6 on 2024-05-10 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="added_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="movie",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
