# Generated by Django 5.0.6 on 2024-05-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(null=True),
        ),
    ]
