# Generated by Django 5.0.6 on 2024-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_movie_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="rating",
            field=models.IntegerField(default=0),
        ),
    ]
