# Generated by Django 5.0.6 on 2024-05-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_avatar_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="added_on",
            field=models.DateField(auto_now=True),
        ),
    ]
