# Generated by Django 5.0.6 on 2024-05-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_review_added_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="review",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
