# Generated by Django 5.0.6 on 2024-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_alter_review_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="updated_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
